apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: livekit-server
  namespace: telephony-ns
spec:
  selector:
    matchLabels:
      app: livekit-server
  template:
    metadata:
      labels:
        app: livekit-server
    spec:
      hostNetwork: true
      containers:
        - name: livekit-server
          image: livekit/livekit-server:v1.9.0
          command: ["--keys", "devkey: devsecret", "--redis-host", "redis.telephony-ns.svc.cluster.local:6379", "--node-ip", "167.71.66.188"]
