apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-sip
  namespace: telephony-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit-sip
  template:
    metadata:
      labels:
        app: livekit-sip
    spec:
      hostNetwork: true
      containers:
        - name: livekit-sip
          image: livekit/sip:latest
          env:
            - name: SIP_CONFIG_BODY
              value: |
                api_key: 'devkey'
                api_secret: 'devsecret'
                ws_url: 'ws://167.71.66.188:7880'
                redis:
                  address: 'redis.telephony-ns.svc.cluster.local:6379'
                sip_port: 5061
                rtp_port:
                  start: 11000
                  end: 11500
                use_external_ip: false
                logging:
                  level: debug
