[general]
static=yes
writeprotect=no

[from-internal]
; Call MicroSIP
exten => 100,1,Dial(SIP/100)
exten => 100,n,Hangup()

; Call MicroSIP 2
exten => 101,1,Dial(SIP/101)
exten => 101,n,Hangup()

; Call LiveKit Room "200"
exten => 200,1,Dial(SIP/livekit/200)
exten => 200,n,Hangup()
