apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: livekit-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`livekit.167.71.66.188.nip.io`)
      kind: Rule
      services:
        - name: livekit-server
          port: 7880
  tls:
    secretName: livekit-tls
