livekit:
  port: 7880
  rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 50050
    use_external_ip: true
  redis:
    address: redis-master.default.svc.cluster.local:6379
  keys:
    devkey: devsecret
podHostNetwork: true
