apiVersion: v1
kind: Secret
metadata:
  name: livekit-secrets
  namespace: telephony-ns
type: Opaque
stringData:
  LIVEKIT_API_KEY: devkey
  LIVEKIT_API_SECRET: devsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-secrets
  namespace: telephony-ns
type: Opaque
stringData:
  GOOGLE_API_KEY: REDACTED_API_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: foodrms-ns
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
