FROM node:20-alpine
WORKDIR /app
ENV RUNNING_IN_DOCKER=true
COPY package*.json ./
COPY node_modules ./node_modules
COPY .next ./.next
COPY public ./public
EXPOSE 80
ENV PORT=80
CMD ["npx", "next", "start"]
