[general]
bindport=5060
bindaddr=0.0.0.0
context=public
disallow=all
allow=ulaw
allow=alaw

[100]
type=friend
context=from-internal
host=dynamic
secret=12345
disallow=all
allow=ulaw
allow=alaw

[livekit]
type=friend
context=from-internal
host=127.0.0.1
port=5061
insecure=port,invite
disallow=all
allow=ulaw
allow=alaw
