# values.yaml
namespace: default

postgres:
  image: postgres:15-alpine
  username: postgres
  password: postgres
  database: foodrms

backend:
  image: foodrms-backend:v2
  environment: Development

frontend:
  image: foodrms-frontend:latest

unifiedApp:
  image: foodrms-unified:latest

pgadmin:
  image: dpage/pgadmin4:latest
  email: admin@foodrms.com
  password: admin

totp:
  image: foodrms-totp:latest
baseDomain: 167.71.66.188.nip.io
