apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-agent
  namespace: telephony-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini-agent
  template:
    metadata:
      labels:
        app: gemini-agent
    spec:
      containers:
        - name: gemini-agent
          image: local-gemini-agent:latest
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secrets
                  key: GOOGLE_API_KEY
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: livekit-secrets
                  key: LIVEKIT_API_KEY
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: livekit-secrets
                  key: LIVEKIT_API_SECRET
            - name: LIVEKIT_URL
              value: ws://167.71.66.188:7880
            - name: BACKEND_URL
              value: http://backend.foodrms-ns.svc.cluster.local:5109
