apiVersion: v1
kind: Service
metadata:
  name: asterisk-headless
  labels:
    app: my-asterisk
spec:
  clusterIP: None
  selector:
    app: my-asterisk
  ports:
  - port: 5060
    targetPort: 5060
    protocol: UDP
    name: sip
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-asterisk
  labels:
    app: my-asterisk
spec:
  serviceName: asterisk-headless
  replicas: 1
  selector:
    matchLabels:
      app: my-asterisk
  template:
    metadata:
      labels:
        app: my-asterisk
    spec:
      containers:
      - name: asterisk
        image: local-asterisk:latest
        imagePullPolicy: Never
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        ports:
        - containerPort: 5060
          protocol: UDP
          name: sip
