apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branch-app
  template:
    metadata:
      labels:
        app: branch-app
    spec:
      containers:
      - name: branch-app
        image: "{{ .Values.branchApp.image }}"
        imagePullPolicy: Never
        env:
        - name: RUNNING_IN_DOCKER
          value: "true"
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: branch-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: branch-app
