apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodrms-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.baseDomain }}
    - api-call.{{ .Values.baseDomain }}
    - pgadmin.{{ .Values.baseDomain }}
    - totp.{{ .Values.baseDomain }}
    - unified-rms.{{ .Values.baseDomain }}
    secretName: foodrms-tls-secret
  rules:
  - host: {{ .Values.baseDomain }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5109
      - path: /Admin
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5109
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5109
      - path: /Identity
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5109
      - path: /uploads
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5109
      - path: /images
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5109
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unified-app
            port:
              number: 80
  - host: unified-rms.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5109
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unified-app
            port:
              number: 80
  # api-call. => Backend API
  - host: api-call.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5109
  - host: pgadmin.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin
            port:
              number: 5050
  - host: totp.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: totp
            port:
              number: 8082
